In [169]:
# load useful libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [171]:
#we display the features
feature_data = pd.read_csv('kaggle_data/features.txt', header=None, sep="  ", names=['feature_names', 'feature_description'], engine='python')
feature_data.head(5)

            feature_names                                feature_description
0          nb_words_title            Number of words in the article's titles
1        nb_words_content                     Number of words in the article
2           pp_uniq_words          Proportion of unique words in the article
3           pp_stop_words  Proportion of stop words (i.e. words predefine...
4  pp_uniq_non-stop_words    Proportion of non-stop words among unique words

In [172]:
#we diplay the train set
list_feature_names = list(feature_data['feature_names'])
train_data = pd.read_csv('kaggle_data/train.csv', header=None, sep=" ", names=list_feature_names)
train_data.head(5)

,nb_words_title,nb_words_content,pp_uniq_words,pp_stop_words,pp_uniq_non-stop_words,nb_links,nb_outside_links,nb_images,nb_videos,ave_word_length,...,pp_neg_words,pp_pos_words_in_nonneutral,ave_polar_pos,min_polar_pos,max_polar_pos,ave_polar_neg,min_polar_neg,max_polar_neg,subj_title,polar_title
2000,9,843,0.5358,2.092000e-09,0.7469,15.0,8,11,1,4,...,0.019230,0.7143,0.4437,0.03333,1.0,-0.3160,-0.8000,-0.05,0.0,0.0
2001,9,805,0.4196,2.165000e-09,0.5693,8.0,7,1,0,4,...,0.025710,0.5349,0.3081,0.05000,0.8,-0.3463,-0.7143,-0.10,0.9,0.3
2002,8,145,0.7594,1.163000e-08,0.8488,7.0,3,0,2,4,...,0.007519,0.8333,0.3673,0.13640,0.5,-0.2000,-0.2000,-0.20,0.0,0.0
2003,12,201,0.6359,9.259000e-09,0.8148,7.0,2,0,0,4,...,0.027030,0.7368,0.3721,0.13640,0.6,-0.4000,-0.4000,-0.40,0.0,0.0
2004,13,673,0.4609,2.500000e-09,0.5950,8.0,7,1,0,4,...,0.021440,0.5625,0.3500,0.05000,0.6,-0.2435,-0.8000,-0.10,0.0,0.0

In [173]:
#display test set
test_data=pd.read_csv('kaggle_data/test-val.csv',header=None,sep=" ",names=list_feature_names)
test_data.head(5)

,nb_words_title,nb_words_content,pp_uniq_words,pp_stop_words,pp_uniq_non-stop_words,nb_links,nb_outside_links,nb_images,nb_videos,ave_word_length,...,pp_neg_words,pp_pos_words_in_nonneutral,ave_polar_pos,min_polar_pos,max_polar_pos,ave_polar_neg,min_polar_neg,max_polar_neg,subj_title,polar_title
0,12,258,0.5745,6.897000e-09,0.6897,4.0,2,0,0,4,...,0.01653,0.7143,0.2967,0.10000,1.0,-0.2344,-0.3,-0.1875,0.125,0.0
1,8,11,0.0000,1.000000e+00,0.0000,0.0,0,0,0,0,...,0.00000,0.0000,0.0000,0.00000,0.0,0.0000,0.0,0.0000,0.525,0.3
2,10,263,0.7249,6.623000e-09,0.8543,6.0,3,2,0,5,...,0.04701,0.5000,0.2617,0.10000,1.0,-0.2170,-0.5,-0.1250,0.000,-0.2
3,13,1281,0.4067,1.422000e-09,0.5903,29.0,4,1,1,4,...,0.01512,0.7500,0.3585,0.03333,1.0,-0.2403,-0.5,-0.0500,0.000,0.0
4,9,107,0.8152,1.538000e-08,0.8154,5.0,2,0,0,4,...,0.02151,0.6667,0.4881,0.28570,1.0,-0.8000,-1.0,-0.6000,0.000,0.0

In [174]:
#we display y the labels
target_data = pd.read_csv('kaggle_data/train-targets.csv', sep=",")
target_data.head(5)

     Id  Prediction
0  2000         882
1  2001        1102
2  2002        1102
3  2003        1001
4  2004        1603

In [175]:
#Data engineering 
#drop irrelevant features (not now)

# 'weekday' encoding
weekday_data=pd.get_dummies(train_data['weekday'],prefix='weekday',drop_first=True)
# 'category' encoding
category_data=pd.get_dummies(train_data['category'],prefix='category',drop_first=True)

other_data=train_data.drop(['weekday','category'],axis=1)

training_data=pd.concat([category_data,weekday_data,other_data],axis=1)

training_data.head(5)

,category_1,category_2,category_3,category_4,category_5,weekday_1,weekday_2,weekday_3,weekday_4,weekday_5,...,pp_neg_words,pp_pos_words_in_nonneutral,ave_polar_pos,min_polar_pos,max_polar_pos,ave_polar_neg,min_polar_neg,max_polar_neg,subj_title,polar_title
2000,1,0,0,0,0,1,0,0,0,0,...,0.019230,0.7143,0.4437,0.03333,1.0,-0.3160,-0.8000,-0.05,0.0,0.0
2001,0,0,0,0,1,0,1,0,0,0,...,0.025710,0.5349,0.3081,0.05000,0.8,-0.3463,-0.7143,-0.10,0.9,0.3
2002,0,0,0,1,0,0,0,0,0,0,...,0.007519,0.8333,0.3673,0.13640,0.5,-0.2000,-0.2000,-0.20,0.0,0.0
2003,0,0,0,1,0,0,1,0,0,0,...,0.027030,0.7368,0.3721,0.13640,0.6,-0.4000,-0.4000,-0.40,0.0,0.0
2004,0,0,0,0,1,0,1,0,0,0,...,0.021440,0.5625,0.3500,0.05000,0.6,-0.2435,-0.8000,-0.10,0.0,0.0

In [176]:
#lets do the same with the test data
weekday_data_test=pd.get_dummies(test_data['weekday'],prefix='weekday',drop_first=True)
category_data_test=pd.get_dummies(test_data['category'],prefix='category',drop_first=True)
other_data_test=test_data.drop(['weekday','category'],axis=1)
testing_data=pd.concat([category_data_test,weekday_data_test,other_data_test],axis=1)
testing_data.head(5)

,category_1,category_2,category_3,category_4,category_5,weekday_1,weekday_2,weekday_3,weekday_4,weekday_5,...,pp_neg_words,pp_pos_words_in_nonneutral,ave_polar_pos,min_polar_pos,max_polar_pos,ave_polar_neg,min_polar_neg,max_polar_neg,subj_title,polar_title
0,0,0,0,0,1,0,0,0,0,0,...,0.01653,0.7143,0.2967,0.10000,1.0,-0.2344,-0.3,-0.1875,0.125,0.0
1,0,0,0,0,1,0,1,0,0,0,...,0.00000,0.0000,0.0000,0.00000,0.0,0.0000,0.0,0.0000,0.525,0.3
2,0,0,0,0,1,0,0,1,0,0,...,0.04701,0.5000,0.2617,0.10000,1.0,-0.2170,-0.5,-0.1250,0.000,-0.2
3,0,0,0,1,0,0,0,0,0,0,...,0.01512,0.7500,0.3585,0.03333,1.0,-0.2403,-0.5,-0.0500,0.000,0.0
4,0,0,0,0,1,0,1,0,0,0,...,0.02151,0.6667,0.4881,0.28570,1.0,-0.8000,-1.0,-0.6000,0.000,0.0

In [185]:
#Data standardization
from sklearn import preprocessing
sc=preprocessing.StandardScaler()

In [178]:
#we are going to load data X and y for regression
print training_data.shape
sc.fit(training_data)
X=sc.transform(training_data)
y=target_data['Prediction'].values

#data is ready for regression

(5000, 52)

In [189]:
from sklearn import cross_validation
folds = cross_validation.KFold(y.size, n_folds=5, shuffle=True, random_state=27)
print y.size

5000

In [190]:
def cross_validate_regr(design_matrix, labels, regressor, cv_folds):
    """ Perform a cross-validation and returns the predictions.
    
    Parameters:
    -----------
    design_matrix: (n_samples, n_features) np.array
        Design matrix for the experiment.
    labels: (n_samples, ) np.array
        Vector of labels.
    regressor:  Regressor instance; must have the following methods:
        - fit(X, y) to train the regressor on the data X, y
        - predict(X) to apply the trained regressor to the data X and return estimates 
    cv_folds: sklearn cross-validation object
        Cross-validation iterator.
        
    Returns:
    -------
    pred: (n_samples, ) np.array
        Vectors of predictions (same order as labels).
    """
    pred = np.zeros(labels.shape)
    for tr, te in cv_folds:
        regressor.fit(design_matrix[tr,:], labels[tr])
        pred[te] = (regressor.predict(design_matrix[te,:]))
    return pred

In [191]:
from sklearn import linear_model
from sklearn import metrics

#operation linear regression
regr=linear_model.LinearRegression()
y_pred=cross_validate_regr(X,y,regressor=regr,cv_folds=folds)
print y_pred
#RMLSE (Root mean squared logarithmic error)
print("Mean squared error: %.3f" % metrics.mean_squared_error(y, y_pred))
print y_pred - y

[ 2999.23139733  1822.86879137  4375.17389371 ...,  3414.61670168
  7156.6639789   2682.58472226]
Mean squared error: 59718307.165
[ 2117.23139733   720.86879137  3273.17389371 ...,  2013.61670168
  6254.6639789   1478.58472226]

In [182]:
#scaling test data and other stuff

X_test = sc.transform(testing_data)